// <auto-generated />
using System;
using FitnessTracker.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    [Migration("20251208183833_SetRepsTracker")]
    partial class SetRepsTracker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FitnessTracker.Models.TrackedPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TrackedPerson");
                });

            modelBuilder.Entity("FitnessTracker.Models.SetsRepsTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CurrentDay")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Set")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkoutTrackerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTrackerId");

                    b.ToTable("SetsRepsTracker");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NormalReps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NormalSets")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDay")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTrackers");
                });

            modelBuilder.Entity("FitnessTracker.Models.SetsRepsTracker", b =>
                {
                    b.HasOne("FitnessTracker.Models.WorkoutTracker", null)
                        .WithMany("setsRepsTrackers")
                        .HasForeignKey("WorkoutTrackerId");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutTracker", b =>
                {
                    b.Navigation("setsRepsTrackers");
                });
#pragma warning restore 612, 618
        }
    }
}
